global using Aven.Contracts.Identifiers;
global using Aven.Toolkit.Core.Identifiers;
global using SchemaRef = Aven.Toolkit.Core.Identifiers.SchemaRef;
global using Aven.Contracts.Operations;
global using OperationError = Aven.Toolkit.Core.Operations.OperationError;
global using OperationValue = Aven.Toolkit.Core.Operations.OperationValue;
global using Aven.Trace.Contracts.Commands;
global using ITraceQueryService = Aven.Toolkit.Tracing.ITraceQueryService;
global using TraceSubjectDto = Aven.Toolkit.Tracing.TraceSubjectDto;
global using TraceLinkDto = Aven.Toolkit.Tracing.TraceLinkDto;
global using TraceInvariantDto = Aven.Toolkit.Tracing.TraceInvariantDto;
global using TraceTimelineItemDto = Aven.Toolkit.Tracing.TraceTimelineItemDto;
global using TraceTimelineResult = Aven.Toolkit.Tracing.TraceTimelineResult;
global using TraceQueryOptions = Aven.Toolkit.Tracing.TraceQueryOptions;
global using TraceStuckQueryOptions = Aven.Toolkit.Tracing.TraceStuckQueryOptions;
global using TraceProjectionOptions = Aven.Toolkit.Tracing.TraceProjectionOptions;
global using TraceProjectionHealth = Aven.Toolkit.Tracing.TraceProjectionHealth;
global using TraceEntityRefDto = Aven.Toolkit.Tracing.TraceEntityRefDto;
global using TraceEntityDetail = Aven.Toolkit.Tracing.TraceEntityDetail;
global using Aven.Trace.Contracts.Responses;
global using Aven.Events.Interfaces;
global using Aven.Events.Models;
global using Aven.Trace.Actors;
global using Aven.Trace.Storage;
