import type { StyleDef } from '../../engine/types.js'

const tokens: StyleDef['tokens'] = {
	'bg-a': '#FBFAF6',
	'tech-fill': 'rgba(255, 255, 255, 0.1)',
	'tech-fill-inner': 'rgba(255, 255, 255, 0.15)',
	'hitl-dash': 'color-mix(in srgb, var(--text) 20%, transparent)',
	border: 'rgba(0, 0, 0, 0.1)',
	'border-soft': 'color-mix(in srgb, var(--border) 35%, transparent)',
	muted: 'rgba(26, 26, 26, 0.45)',
	text: '#1a1a1a',
	'brand-accent': '#e6b34d',
	'banner-divider': 'color-mix(in srgb, var(--text) 12%, transparent)',
	'row-divider': 'color-mix(in srgb, var(--border) 55%, transparent)',
	'radius-2xl': '2rem',
	'radius-md': '1rem',
	'font-sans': "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
}

const selectors: StyleDef['selectors'] = {
	'*, *::before, *::after': { boxSizing: 'border-box' },
	':host': {
		fontFamily: 'var(--font-sans)',
		background: 'var(--bg-a)',
		color: 'var(--text)',
		margin: '0',
		minHeight: '100%',
		height: '100%',
	},
	'.bs-ui-container': {
		padding: '1.25rem 1.5rem',
		borderRadius: 'var(--radius-2xl)',
		background: 'var(--tech-fill)',
		border: 'none',
	},
	'.bs-card': {
		background: 'var(--tech-fill)',
		border: '1px dashed var(--hitl-dash)',
		borderRadius: 'var(--radius-2xl)',
		padding: '18px 20px',
		marginBottom: '16px',
	},
	'.bs-card h4': {
		margin: '0 0 8px 0',
		fontSize: '10px',
		fontWeight: '700',
		color: 'var(--muted)',
		textTransform: 'uppercase',
		letterSpacing: '0.12em',
		opacity: '0.55',
	},
	'.bs-card .big': {
		fontSize: '15px',
		fontWeight: '700',
		color: 'var(--text)',
		marginBottom: '4px',
	},
	'.bs-card .line': {
		fontSize: '13px',
		color: 'var(--text)',
		marginTop: '2px',
		whiteSpace: 'pre-wrap',
		wordBreak: 'break-word',
	},
	'.bs-card .muted': {
		color: 'var(--muted)',
		fontSize: '12px',
		marginTop: '2px',
	},
	'.bs-grid': {
		display: 'grid',
		gap: '16px',
		gridTemplateColumns: '1fr 1fr',
		marginBottom: '16px',
	},
	'.bs-banner': {
		background: 'var(--tech-fill-inner)',
		border: '1px dashed var(--hitl-dash)',
		borderRadius: 'var(--radius-2xl)',
		padding: '14px 20px',
		marginBottom: '16px',
		fontSize: '13px',
	},
	'.bs-banner-hero': {
		display: 'grid',
		gridTemplateColumns: '1fr auto',
		gap: '12px 24px',
		alignItems: 'end',
	},
	'.bs-banner-title': {
		fontSize: '1.1rem',
		fontWeight: '800',
		letterSpacing: '-0.02em',
		color: 'var(--text)',
		textTransform: 'capitalize',
	},
	'.bs-banner-sub': {
		fontSize: '10px',
		fontWeight: '700',
		color: 'var(--muted)',
		textTransform: 'uppercase',
		letterSpacing: '0.08em',
		marginTop: '6px',
	},
	'.bs-banner-money': {
		fontSize: '1.35rem',
		fontWeight: '800',
		fontFamily: 'ui-monospace, Menlo, monospace',
		fontVariantNumeric: 'tabular-nums',
		color: 'var(--brand-accent)',
		textAlign: 'right',
	},
	'.bs-banner-money .bs-banner-sub': { textAlign: 'right' },
	'.bs-field-label': {
		fontSize: '9px',
		fontWeight: '700',
		color: 'var(--muted)',
		textTransform: 'uppercase',
		letterSpacing: '0.06em',
		marginTop: '4px',
	},
	'.bs-field-val': {
		fontSize: '0.95rem',
		fontWeight: '700',
		fontFamily: 'ui-monospace, Menlo, monospace',
		fontVariantNumeric: 'tabular-nums',
	},
	'.bs-banner-fields': {
		display: 'grid',
		gridTemplateColumns: 'repeat(auto-fit, minmax(130px, 1fr))',
		gap: '10px 18px',
		marginTop: '12px',
		paddingTop: '10px',
		borderTop: '1px solid var(--banner-divider)',
	},
	'.bs-banner-fields--compact': {
		justifyContent: 'start',
		justifyItems: 'start',
		gridTemplateColumns: 'repeat(auto-fill, minmax(108px, max-content))',
		gap: '10px 14px',
	},
	'.bs-banner-fields--compact .bs-field-val': {
		fontSize: '0.8125rem',
		fontWeight: '700',
		lineHeight: '1.25',
	},
	'.bs-banner-fields--compact .bs-field-cell--nowrap .bs-field-val': {
		whiteSpace: 'nowrap',
	},
	'.bs-items-wrap': {
		background: 'var(--tech-fill)',
		border: '1px dashed var(--hitl-dash)',
		borderRadius: 'var(--radius-2xl)',
		overflow: 'auto',
		marginBottom: '16px',
	},
	'.bs-items': {
		width: '100%',
		borderCollapse: 'collapse',
		fontSize: '13px',
	},
	'.bs-items thead th': {
		textAlign: 'left',
		background: 'var(--tech-fill-inner)',
		padding: '10px 12px',
		borderBottom: '1px solid var(--border-soft)',
		fontWeight: '700',
		fontSize: '10px',
		textTransform: 'uppercase',
		letterSpacing: '0.05em',
		color: 'var(--muted)',
	},
	'.bs-items thead th.num': { textAlign: 'right' },
	'.bs-items tbody td': {
		padding: '10px 12px',
		borderBottom: '1px solid var(--row-divider)',
		verticalAlign: 'top',
	},
	'.bs-items tbody tr:last-child td': { borderBottom: 'none' },
	'.bs-items .num': {
		textAlign: 'right',
		fontFamily: 'ui-monospace, Menlo, monospace',
		fontVariantNumeric: 'tabular-nums',
		whiteSpace: 'nowrap',
	},
	'.bs-items .num--neg': {
		color: 'color-mix(in srgb, var(--text) 75%, #b91c1c)',
	},
	'.bs-desc-title': {
		fontWeight: '700',
		color: 'var(--text)',
		lineHeight: '1.35',
	},
	'.bs-desc-body': {
		fontSize: '12px',
		color: 'var(--muted)',
		lineHeight: '1.45',
		marginTop: '3px',
		whiteSpace: 'pre-line',
	},
	'.bs-fx-hint': {
		fontSize: '10px',
		color: 'var(--muted)',
		marginTop: '4px',
		fontStyle: 'italic',
	},
	'.bs-desc-title:empty, .bs-desc-body:empty, .bs-fx-hint:empty': { display: 'none' },
	'.bs-notes': {
		fontSize: '13px',
		lineHeight: '1.5',
		whiteSpace: 'pre-line',
		color: 'var(--text)',
	},
	'@media (max-width: 760px)': {
		'.bs-grid': { gridTemplateColumns: '1fr' },
	},
	'@media (max-width: 560px)': {
		'.bs-banner-hero': { gridTemplateColumns: '1fr' },
	},
}

export const bankStatementStyle: StyleDef = {
	tokens,
	selectors,
}
