global using Aven.Contracts.Identifiers;
global using Aven.Toolkit.Core.Identifiers;
global using SchemaRef = Aven.Toolkit.Core.Identifiers.SchemaRef;
global using Aven.Contracts.Operations;
global using OperationError = Aven.Toolkit.Core.Operations.OperationError;
global using OperationValue = Aven.Toolkit.Core.Operations.OperationValue;
global using Aven.Events.Interfaces;
global using Aven.Resources.Artifacts.Contracts;
global using Aven.Toolkit.Artifacts;
global using Aven.Toolkit.Artifacts.Abstractions;