[workspace]
members = [
    "crates/core",
    "crates/postgres",
    "crates/client",
    "crates/server",
    "crates/tauri",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Aven"]
edition = "2021"
rust-version = "1.93"
license = "MIT OR Apache-2.0"
publish = false

[workspace.lints.rust]
unsafe_code = "forbid"
