global using Aven.Contracts.Identifiers;
global using Aven.Toolkit.Core.Identifiers;
global using SchemaRef = Aven.Toolkit.Core.Identifiers.SchemaRef;
global using Aven.Contracts.Operations;
global using OperationError = Aven.Toolkit.Core.Operations.OperationError;
global using OperationValue = Aven.Toolkit.Core.Operations.OperationValue;
global using Aven.Resources.Human.Contracts.Enums;
global using Aven.Resources.Human.Contracts.Models;
global using Aven.Resources.Human.Contracts.Protocol;
global using Aven.Events.Interfaces;
