import type { StyleDef } from '../../engine/types.js'
import { withBrand } from '../../brand-style.js'

// Shared brand layer provides colours/radii/fonts/ink. Todos keeps its navy
// action accent and the row divider.
const tokens: StyleDef['tokens'] = {
	'row-divider': 'color-mix(in srgb, var(--border) 55%, transparent)',
	'brand-accent': '#1e293b',
	'brand-accent-fg': '#f8fafc',
}

const selectors: StyleDef['selectors'] = {
	'.td-ui-container': {
		minHeight: '100%',
		maxWidth: 'var(--max-w)',
		margin: '0 auto',
		padding: 'var(--pad-card)',
		borderRadius: 'var(--radius-card)',
		background: 'var(--tech-fill)',
		border: 'none',
		display: 'flex',
		flexDirection: 'column',
		boxSizing: 'border-box',
		fontFamily: 'var(--font-sans)',
		color: 'var(--text)',
		letterSpacing: '-0.02em',
	},
	'.td-card': {
		background: 'var(--tech-fill)',
		border: '1px solid var(--border)',
		borderRadius: 'var(--radius-2xl)',
		padding: '18px 20px',
		marginBottom: '16px',
	},
	'.td-card:last-child': { marginBottom: '0' },
	'.td-card h4': {
		margin: '0 0 10px 0',
		fontSize: '10px',
		fontWeight: '600',
		color: 'var(--muted)',
		textTransform: 'uppercase',
		letterSpacing: '0.12em',
		opacity: '0.55',
	},
	'.td-banner-grid': {
		display: 'grid',
		gridTemplateColumns: '1fr auto',
		gap: '12px 24px',
		alignItems: 'end',
	},
	'.td-eyebrow': {
		display: 'block',
		fontSize: '10px',
		fontWeight: '600',
		color: 'var(--muted)',
		textTransform: 'uppercase',
		letterSpacing: '0.08em',
		opacity: '0.55',
		marginBottom: '6px',
	},
	'.td-banner-title': {
		margin: '0',
		fontSize: '1.1rem',
		fontWeight: '600',
		letterSpacing: '-0.02em',
		color: 'var(--text)',
		lineHeight: '1.2',
	},
	'.td-field-label': {
		display: 'block',
		fontSize: '9px',
		fontWeight: '600',
		color: 'var(--muted)',
		textTransform: 'uppercase',
		letterSpacing: '0.06em',
		marginBottom: '4px',
	},
	'.td-banner-stat': { textAlign: 'right' },
	'.td-banner-stat .td-field-label': { textAlign: 'right' },
	'.td-banner-accent': {
		fontSize: '1.35rem',
		fontWeight: '600',
		fontFamily: 'ui-monospace, Menlo, monospace',
		fontVariantNumeric: 'tabular-nums',
		color: 'var(--brand-accent)',
		lineHeight: '1.15',
	},
	'.td-card--list': {
		flex: '1',
		minHeight: '0',
		display: 'flex',
		flexDirection: 'column',
		marginBottom: '0',
		// Each task item is its own dashed mini-card now — drop the container's border/padding.
		border: 'none',
		background: 'transparent',
		padding: '0',
	},
	'.td-add-form': {
		display: 'flex',
		gap: '10px',
		flexWrap: 'wrap',
		alignItems: 'stretch',
	},
	'.td-input': {
		flex: '1',
		minWidth: '140px',
		font: 'inherit',
		color: 'inherit',
		background: 'var(--tech-fill-inner)',
		border: '1px solid var(--border-soft)',
		borderRadius: 'var(--radius-md)',
		padding: '0.55rem 0.85rem',
		outline: 'none',
	},
	'.td-input:focus': {
		borderColor: 'var(--brand-accent)',
		boxShadow: '0 0 0 2px color-mix(in srgb, var(--brand-accent) 28%, transparent)',
	},
	'.td-btn': {
		font: 'inherit',
		cursor: 'pointer',
		borderRadius: 'var(--radius-md)',
		padding: '0.5rem 0.85rem',
		fontWeight: '500',
		fontSize: '0.8125rem',
		transition: 'background 0.15s ease, border-color 0.15s ease, filter 0.15s ease',
	},
	'.td-btn--primary': {
		background: 'var(--brand-accent)',
		color: 'var(--brand-accent-fg)',
		border: '1px solid color-mix(in srgb, var(--text) 12%, transparent)',
	},
	'.td-btn--primary:hover': { filter: 'brightness(1.03)' },
	'.td-btn--ghost': {
		background: 'var(--tech-fill-inner)',
		border: '1px solid var(--border-soft)',
		color: 'var(--text)',
	},
	'.td-btn--ghost:disabled': { opacity: '0.45', cursor: 'not-allowed' },
	'.td-btn--icon': {
		border: 'none',
		background: 'transparent',
		color: 'var(--muted)',
		fontSize: '1.25rem',
		lineHeight: '1',
		padding: '0.2rem 0.45rem',
		fontWeight: '400',
	},
	'.td-btn--icon:hover': { color: '#dc2626' },
	'.td-list': {
		listStyle: 'none',
		margin: '0',
		padding: '0',
		flex: '1',
		minHeight: '120px',
		overflowY: 'auto',
		display: 'flex',
		flexDirection: 'column',
		gap: '10px',
	},
	'.td-list li.empty': {
		textAlign: 'center',
		color: 'var(--muted)',
		padding: '1.5rem 1rem',
		fontSize: '13px',
		border: '1px solid var(--border)',
		borderRadius: 'var(--radius-md)',
		marginTop: '2px',
	},
	'.td-list:has(.td-row) li[data-empty="true"]': { display: 'none' },
	'.td-row': {
		display: 'flex',
		alignItems: 'center',
		gap: '0.85rem',
		padding: '12px 14px',
		border: '1px solid var(--border)',
		borderRadius: 'var(--radius-md)',
		background: 'var(--tech-fill)',
		animation: 'td-slide-in 0.18s ease-out',
	},
	'.td-row input[type="checkbox"]': {
		appearance: 'none',
		WebkitAppearance: 'none',
		width: '1.4rem',
		height: '1.4rem',
		margin: '0',
		flexShrink: '0',
		borderRadius: '50%',
		background: 'var(--tech-fill-inner)',
		border: '1px solid var(--border)',
		cursor: 'pointer',
		display: 'grid',
		placeContent: 'center',
		transition: 'background 0.15s ease, border-color 0.15s ease, box-shadow 0.15s ease',
	},
	'.td-row input[type="checkbox"]:checked': {
		background: 'var(--brand-accent)',
		borderColor: 'color-mix(in srgb, var(--text) 14%, transparent)',
	},
	'.td-row input[type="checkbox"]::after': {
		content: '""',
		width: '0.32rem',
		height: '0.58rem',
		border: 'solid var(--brand-accent-fg)',
		borderWidth: '0 2px 2px 0',
		transform: 'rotate(45deg) translate(-0.5px, -1px)',
		opacity: '0',
		boxSizing: 'content-box',
	},
	'.td-row input[type="checkbox"]:checked::after': { opacity: '1' },
	'.td-row-text': {
		flex: '1',
		outline: 'none',
		padding: '0.2rem 0.35rem',
		borderRadius: '0.35rem',
		fontSize: '15px',
		whiteSpace: 'pre-wrap',
		wordBreak: 'break-word',
	},
	'.td-row.done .td-row-text': {
		textDecoration: 'line-through',
		color: 'var(--muted)',
	},
	'.td-list-footer': {
		display: 'flex',
		justifyContent: 'flex-end',
		marginTop: '12px',
		paddingTop: '12px',
		borderTop: '1px solid color-mix(in srgb, var(--text) 10%, transparent)',
		flexShrink: '0',
	},
	'@keyframes td-slide-in': {
		from: { opacity: '0', transform: 'translateY(-3px)' },
		to: { opacity: '1', transform: 'translateY(0)' },
	},
	'@media (max-width: 560px)': {
		'.td-banner-grid': { gridTemplateColumns: '1fr' },
		'.td-banner-stat, .td-banner-stat .td-field-label': { textAlign: 'left' },
	},
}

export const todoStyle: StyleDef = withBrand({ tokens, selectors })
