import type { StyleDef } from '../../engine/types.js'

const tokens: StyleDef['tokens'] = {
	'bg-a': '#FBFAF6',
	'tech-fill': 'rgba(255, 255, 255, 0.1)',
	'tech-fill-inner': 'rgba(255, 255, 255, 0.15)',
	'hitl-dash': 'color-mix(in srgb, var(--text) 20%, transparent)',
	border: 'rgba(0, 0, 0, 0.1)',
	muted: 'rgba(26, 26, 26, 0.45)',
	text: '#1a1a1a',
	'brand-accent': '#e6b34d',
	'radius-2xl': '2rem',
	'radius-md': '1rem',
	'font-sans': "'Chillax', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
}

const selectors: StyleDef['selectors'] = {
	'*, *::before, *::after': { boxSizing: 'border-box' },
	':host': {
		fontFamily: 'var(--font-sans)',
		background: 'var(--bg-a)',
		color: 'var(--text)',
		margin: '0',
		minHeight: '100%',
		height: '100%',
		letterSpacing: '-0.015em',
	},
	'.cv-shell': {
		padding: '1.25rem 1.5rem',
		borderRadius: 'var(--radius-2xl)',
		background: 'var(--tech-fill)',
		border: 'none',
		maxWidth: '52rem',
		margin: '0 auto',
	},
	'.cv-hero': {
		background: 'var(--tech-fill-inner)',
		border: '1px dashed var(--hitl-dash)',
		borderRadius: 'var(--radius-2xl)',
		padding: '1rem 1.25rem 1.1rem',
		marginBottom: '1rem',
	},
	'.cv-hero-eyebrow': {
		fontSize: '10px',
		fontWeight: '600',
		letterSpacing: '0.1em',
		textTransform: 'uppercase',
		color: 'var(--muted)',
		opacity: '0.65',
		marginBottom: '0.35rem',
	},
	'.cv-hero-title': {
		margin: '0',
		fontSize: '1.2rem',
		fontWeight: '600',
		lineHeight: '1.25',
		letterSpacing: '-0.02em',
	},
	'.cv-hero-meta': {
		display: 'flex',
		flexWrap: 'wrap',
		gap: '0.65rem 1.25rem',
		marginTop: '0.75rem',
		fontSize: '12px',
		color: 'var(--muted)',
	},
	'.cv-hero-meta strong': { color: 'var(--text)', fontWeight: '500' },
	'.cv-parties': {
		display: 'grid',
		gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
		gap: '12px',
		marginBottom: '1rem',
	},
	'.cv-party': {
		background: 'var(--tech-fill)',
		border: '1px dashed var(--hitl-dash)',
		borderRadius: 'var(--radius-2xl)',
		padding: '14px 16px',
	},
	'.cv-party-role': {
		fontSize: '10px',
		fontWeight: '600',
		textTransform: 'uppercase',
		letterSpacing: '0.1em',
		color: 'var(--brand-accent)',
		marginBottom: '6px',
	},
	'.cv-party-name': { fontSize: '15px', fontWeight: '600', lineHeight: '1.3', marginBottom: '4px' },
	'.cv-party-line': {
		fontSize: '12px',
		color: 'var(--muted)',
		lineHeight: '1.45',
		marginTop: '3px',
		whiteSpace: 'pre-line',
	},
	'.cv-preamble': {
		background: 'var(--tech-fill)',
		border: '1px dashed var(--hitl-dash)',
		borderRadius: 'var(--radius-2xl)',
		padding: '14px 18px',
		marginBottom: '1rem',
		fontSize: '13px',
		lineHeight: '1.55',
		color: 'var(--text)',
		whiteSpace: 'pre-line',
	},
	'.cv-preamble h3': {
		margin: '0 0 8px',
		fontSize: '10px',
		fontWeight: '600',
		textTransform: 'uppercase',
		letterSpacing: '0.08em',
		color: 'var(--muted)',
	},
	'.cv-defs': { marginBottom: '1rem', padding: '0 4px' },
	'.cv-defs h3': {
		margin: '0 0 10px',
		fontSize: '10px',
		fontWeight: '600',
		textTransform: 'uppercase',
		letterSpacing: '0.08em',
		color: 'var(--muted)',
	},
	'.cv-def-row': {
		display: 'grid',
		gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 2.2fr)',
		gap: '10px 18px',
		padding: '10px 0',
		borderBottom: '1px solid color-mix(in srgb, var(--border) 45%, transparent)',
		fontSize: '12px',
	},
	'.cv-def-row:last-child': { borderBottom: 'none' },
	'.cv-def-term': { fontWeight: '600', color: 'var(--text)' },
	'.cv-def-body': { color: 'var(--muted)', lineHeight: '1.45' },
	'.cv-clauses': { marginBottom: '1rem' },
	'.cv-clause': {
		background: 'var(--tech-fill-inner)',
		border: '1px dashed var(--hitl-dash)',
		borderRadius: 'var(--radius-md)',
		padding: '12px 16px 14px',
		marginBottom: '10px',
	},
	'.cv-clause-head': {
		display: 'flex',
		flexWrap: 'wrap',
		alignItems: 'baseline',
		gap: '6px 12px',
		marginBottom: '8px',
	},
	'.cv-clause-num': {
		fontFamily: 'ui-monospace, Menlo, monospace',
		fontSize: '12px',
		fontWeight: '600',
		color: 'var(--brand-accent)',
	},
	'.cv-clause-title': { fontSize: '14px', fontWeight: '600' },
	'.cv-clause-body': {
		fontSize: '13px',
		lineHeight: '1.55',
		whiteSpace: 'pre-line',
		color: 'var(--text)',
	},
	'.cv-clause-num:empty, .cv-clause-title:empty, .cv-clause-body:empty, .cv-sign-meta:empty': {
		display: 'none',
	},
	'.cv-clause-head:empty': { display: 'none', marginBottom: '0' },
	'.cv-subclause': {
		marginTop: '10px',
		paddingLeft: '12px',
		borderLeft: '2px solid color-mix(in srgb, var(--brand-accent) 55%, transparent)',
	},
	'.cv-subclause-label': { fontSize: '12px', fontWeight: '600', marginBottom: '4px', color: 'var(--muted)' },
	'.cv-subclause-body': { fontSize: '12px', lineHeight: '1.5', color: 'var(--text)', whiteSpace: 'pre-line' },
	'.cv-signatures': {
		background: 'var(--tech-fill)',
		border: '1px dashed var(--hitl-dash)',
		borderRadius: 'var(--radius-2xl)',
		padding: '14px 18px 18px',
		marginBottom: '10px',
	},
	'.cv-signatures h3': {
		margin: '0 0 12px',
		fontSize: '10px',
		fontWeight: '600',
		textTransform: 'uppercase',
		letterSpacing: '0.08em',
		color: 'var(--muted)',
	},
	'.cv-sign-grid': {
		display: 'grid',
		gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
		gap: '14px',
	},
	'.cv-sign-block': {
		minHeight: '72px',
		paddingTop: '6px',
		borderTop: '1px solid color-mix(in srgb, var(--text) 10%, transparent)',
	},
	'.cv-sign-party': {
		fontSize: '10px',
		fontWeight: '600',
		textTransform: 'uppercase',
		letterSpacing: '0.06em',
		color: 'var(--muted)',
		marginBottom: '4px',
	},
	'.cv-sign-name': { fontSize: '13px', fontWeight: '600' },
	'.cv-sign-meta': { fontSize: '11px', color: 'var(--muted)', marginTop: '4px' },
	'.cv-footnote': {
		fontSize: '11px',
		lineHeight: '1.45',
		color: 'var(--muted)',
		fontStyle: 'italic',
		padding: '0 4px 8px',
	},
	'@media (max-width: 560px)': {
		'.cv-def-row': { gridTemplateColumns: '1fr' },
	},
}

export const contractStyle: StyleDef = {
	tokens,
	selectors,
}
