import { type Kysely, sql } from 'kysely'

// board 0098 — MULTI-AGENT extraction, mirroring the legacy OCR pipeline (parties agent + body agent).
// The single overloaded pass under-filled parties, so add a focused PARTIES pass (parties_prompt +
// parties_schema = ONLY the party objects) alongside the BODY schema (everything else). The
// extract_document actor runs both vision calls on the same page and merges the parties in — each pass
// sees a small focused schema, so gemma4-31b fills each reliably. Flow config only; forward-only.

const INV_BODY = {"type": "object", "additionalProperties": false, "required": ["header", "totals", "statements"], "properties": {"header": {"type": "object", "additionalProperties": false, "properties": {"document_kind": {"type": ["string", "null"], "description": "invoice / credit_note / …"}, "currency": {"type": ["string", "null"], "description": "ISO 4217, e.g. USD/EUR"}, "invoice_number": {"type": ["string", "null"], "description": "Rechnungsnummer exactly as printed"}, "order_number": {"type": ["string", "null"]}, "customer_number": {"type": ["string", "null"]}, "issue_date": {"type": ["string", "null"], "description": "YYYY-MM-DD"}, "due_date": {"type": ["string", "null"], "description": "YYYY-MM-DD"}}}, "totals": {"type": "object", "additionalProperties": false, "properties": {"subtotal": {"type": ["number", "null"], "description": "net subtotal"}, "tax_total": {"type": ["number", "null"], "description": "total VAT"}, "invoice_total": {"type": ["number", "null"], "description": "the FINAL gross total due (Summe / Fälliger Betrag / Rechnungsbetrag)"}, "tax_breakdown": {"type": "array", "items": {"type": "object", "additionalProperties": false, "properties": {"tax_rate_percent": {"type": ["number", "null"]}, "tax_amount": {"type": ["number", "null"]}, "net_subtotal": {"type": ["number", "null"]}}}}}}, "total_outstanding": {"type": ["number", "null"], "description": "open amount still due"}, "payments": {"type": "array", "items": {"type": "object", "additionalProperties": false, "properties": {"date": {"type": ["string", "null"]}, "amount": {"type": ["number", "null"]}, "method": {"type": ["string", "null"]}}}}, "statements": {"type": "array", "items": {"type": "object", "additionalProperties": false, "properties": {"service_period": {"type": ["string", "null"], "description": "Leistungszeitraum verbatim"}, "line_items": {"type": "array", "items": {"type": "object", "additionalProperties": false, "properties": {"position": {"type": ["string", "null"]}, "description": {"type": ["string", "null"], "description": "the position text"}, "title": {"type": ["string", "null"]}, "quantity": {"type": ["number", "null"]}, "quantity_unit": {"type": ["string", "null"]}, "unit_price": {"type": ["number", "null"]}, "tax_rate_percent": {"type": ["number", "null"]}, "amount": {"type": ["number", "null"], "description": "line total"}}}}}}}}} as unknown as Record<string, unknown>
const INV_PARTIES = {"type": "object", "additionalProperties": false, "required": ["vendor", "buyer"], "properties": {"vendor": {"type": ["object", "null"], "additionalProperties": false, "properties": {"name": {"type": ["string", "null"], "description": "vendor/biller (the issuer) legal entity name ONLY"}, "street": {"type": ["string", "null"], "description": "street + house number ONLY"}, "postal_code": {"type": ["string", "null"], "description": "PLZ / ZIP ONLY (e.g. 80469)"}, "city": {"type": ["string", "null"], "description": "city / Ort ONLY (e.g. München)"}, "country": {"type": ["string", "null"], "description": "full country name in English"}, "email": {"type": ["string", "null"]}, "phone": {"type": ["string", "null"]}, "tax_id": {"type": ["string", "null"], "description": "VAT-ID / USt-IdNr ONLY (e.g. DE123456789) — never an address"}, "tax_number": {"type": ["string", "null"], "description": "German Steuernummer ONLY"}, "contact_name": {"type": ["string", "null"], "description": "Ansprechpartner (a natural person)"}, "banking_accounts": {"type": "array", "items": {"type": "object", "additionalProperties": false, "properties": {"iban": {"type": ["string", "null"]}, "bic": {"type": ["string", "null"]}, "bank_name": {"type": ["string", "null"]}}}}}}, "buyer": {"type": ["object", "null"], "additionalProperties": false, "properties": {"name": {"type": ["string", "null"], "description": "buyer/recipient (billed-to) legal entity name ONLY"}, "street": {"type": ["string", "null"], "description": "street + house number ONLY"}, "postal_code": {"type": ["string", "null"], "description": "PLZ / ZIP ONLY (e.g. 80469)"}, "city": {"type": ["string", "null"], "description": "city / Ort ONLY (e.g. München)"}, "country": {"type": ["string", "null"], "description": "full country name in English"}, "email": {"type": ["string", "null"]}, "phone": {"type": ["string", "null"]}, "tax_id": {"type": ["string", "null"], "description": "VAT-ID / USt-IdNr ONLY (e.g. DE123456789) — never an address"}, "tax_number": {"type": ["string", "null"], "description": "German Steuernummer ONLY"}, "contact_name": {"type": ["string", "null"], "description": "Ansprechpartner (a natural person)"}, "banking_accounts": {"type": "array", "items": {"type": "object", "additionalProperties": false, "properties": {"iban": {"type": ["string", "null"]}, "bic": {"type": ["string", "null"]}, "bank_name": {"type": ["string", "null"]}}}}}}}} as unknown as Record<string, unknown>
const BANK_BODY = {"type": "object", "additionalProperties": false, "required": ["currency", "transactions"], "properties": {"statement_kind": {"type": ["string", "null"], "enum": ["periodic_account_statement", "credit_card_statement", "savings_account_statement", "fee_or_service_statement", "other", null]}, "currency": {"type": ["string", "null"], "description": "ISO 4217 account currency"}, "period_start": {"type": ["string", "null"], "description": "YYYY-MM-DD"}, "period_end": {"type": ["string", "null"], "description": "YYYY-MM-DD"}, "opening_balance": {"type": ["number", "null"]}, "closing_balance": {"type": ["number", "null"]}, "account_overview": {"type": ["object", "null"], "additionalProperties": false, "properties": {"iban": {"type": ["string", "null"]}, "bic": {"type": ["string", "null"]}, "account_number": {"type": ["string", "null"]}, "product_name": {"type": ["string", "null"]}}}, "transactions": {"type": "array", "description": "every posted line", "items": {"type": "object", "additionalProperties": false, "required": ["description", "amount"], "properties": {"booking_date": {"type": ["string", "null"], "description": "Datum Buchung, YYYY-MM-DD"}, "value_date": {"type": ["string", "null"], "description": "Datum Beleg/Wertstellung, YYYY-MM-DD"}, "title": {"type": ["string", "null"]}, "description": {"type": ["string", "null"], "description": "Verwendungszweck"}, "amount": {"type": ["number", "null"], "description": "signed total in account currency (debits negative)"}, "balance_after": {"type": ["number", "null"], "description": "running balance after this line"}, "counterparty_name": {"type": ["string", "null"], "description": "Empfänger/Auftraggeber/merchant"}, "counterparty_iban": {"type": ["string", "null"]}, "original_currency": {"type": ["string", "null"], "description": "foreign Währung, ISO 4217"}, "original_amount": {"type": ["number", "null"], "description": "foreign Betrag"}, "exchange_rate": {"type": ["string", "null"], "description": "Kurs/Umrechnungskurs"}, "fx_surcharge_eur": {"type": ["number", "null"], "description": "Währungsumrechnung surcharge EUR"}, "foreign_exchange_fee_percent": {"type": ["number", "null"], "description": "x% Währungsumrechnung as number"}}}}, "notes": {"type": ["string", "null"]}}} as unknown as Record<string, unknown>
const BANK_PARTIES = {"type": "object", "additionalProperties": false, "required": ["account_holder"], "properties": {"account_holder": {"type": ["object", "null"], "additionalProperties": false, "properties": {"name": {"type": ["string", "null"]}, "street": {"type": ["string", "null"]}, "postal_code": {"type": ["string", "null"]}, "city": {"type": ["string", "null"]}, "country": {"type": ["string", "null"]}, "email": {"type": ["string", "null"]}, "phone": {"type": ["string", "null"]}, "tax_id": {"type": ["string", "null"]}, "contact_name": {"type": ["string", "null"]}}}, "institution": {"type": ["object", "null"], "additionalProperties": false, "properties": {"name": {"type": ["string", "null"]}, "city": {"type": ["string", "null"]}}}}} as unknown as Record<string, unknown>
const PARTIES_PROMPT = "You are a document-understanding engine focused ONLY on the PARTIES of a business document (the vendor/biller, the buyer/recipient, and \u2014 on a statement \u2014 the account holder + institution). Call the `emit` tool exactly once. The tool schema is the source of truth. For EACH party, fill the COMPLETE printed block whenever the page shows it: legal `name`; the full postal address split into `street`, `postal_code` (PLZ/ZIP), `city`, `country` (full English name); `email`; `phone`; `banking_accounts`; and the BARE `tax_id` (VAT-ID digits only) + `tax_number` (Steuernummer only) \u2014 strip any printed label such as 'USt-IdNr.:', 'VAT', 'DE VAT'. Read the whole letterhead, footer and imprint \u2014 a PLZ+Ort, e-mail or IBAN printed anywhere belongs on the party even if not next to the name. Use null only when the document truly lacks the value; never invent."

function asJson(v: unknown): unknown { return typeof v === 'string' ? JSON.parse(v) : v }

async function split(db: Kysely<unknown>, flowId: string, body: Record<string, unknown>, parties: Record<string, unknown>): Promise<void> {
	const res = await sql<{ nodes: unknown }>`SELECT nodes FROM flow WHERE id = ${flowId}`.execute(db)
	const row = res.rows[0]
	if (!row) return
	const nodes = asJson(row.nodes) as Array<Record<string, unknown>>
	for (const n of nodes) {
		if (n.actor !== 'extract_document') continue
		n.schema = body
		n.parties_schema = parties
		n.parties_prompt = PARTIES_PROMPT
	}
	await sql`UPDATE flow SET nodes = ${JSON.stringify(nodes)}::jsonb WHERE id = ${flowId}`.execute(db)
}

export async function up(db: Kysely<unknown>): Promise<void> {
	await split(db, 'capture', INV_BODY, INV_PARTIES)
	await split(db, 'capture-bank', BANK_BODY, BANK_PARTIES)
}

export async function down(_db: Kysely<unknown>): Promise<void> {
	// forward-only (flow config).
}
