use std::collections::HashMap;
use std::io::Read;
use std::path::Path;

fn main() {
	// `sherpa-onnx-sys` emits the C++ runtime + Foundation link directives only
	// for `target_os = "linux" | "macos"`; for iOS its build script falls through
	// to a no-op. Statically linking sherpa-onnx (+ onnxruntime) on iOS therefore
	// leaves libc++ and Foundation symbols unresolved at link time. Supply them
	// here, gated on the iOS target and the `local-voice` feature (which pulls in
	// the sherpa-onnx static libs). NOTE: build scripts compile for the HOST, so
	// `cfg!(target_os = ...)` would report macOS — read the real *target* from
	// CARGO_CFG_TARGET_OS instead.
	let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
	if target_os == "ios" && std::env::var_os("CARGO_FEATURE_LOCAL_VOICE").is_some() {
		println!("cargo:rustc-link-lib=c++");
		println!("cargo:rustc-link-lib=framework=Foundation");
	}

	// iOS + llama.cpp link fix. For a `staticlib`, cargo BUNDLES native static libs into the
	// final `libapp.a` by object *basename*. ggml-cpu ships duplicate basenames (`quants.c.o`,
	// `repack.cpp.o` — the generic source AND its `arch/arm/` variant compile to the same
	// basename; `ar` flattens paths), so bundling clobbers one of each → the ggml-cpu symbol
	// definitions (`ggml_compute_forward_*`) get dropped → "undefined symbols for architecture
	// arm64" at the xcodebuild link. macOS links the `.a` directly (no bundling) and is fine.
	// Fix: after llama-cpp-sys-2 built the archives (dep order) and BEFORE our staticlib link,
	// rewrite each ggml `.a` so every member name is unique, then `ranlib` to rebuild its index.
	if target_os == "ios" && std::env::var_os("CARGO_FEATURE_LOCAL_LLAMA").is_some() {
		uniquify_ggml_archives();
	}

	tauri_build::build()
}

/// Find the ggml static libs in the sibling `llama-cpp-sys-2-*/out/lib` build dir(s) and make
/// each archive's member names unique. Best-effort: failures warn, never panic.
fn uniquify_ggml_archives() {
	let Ok(out_dir) = std::env::var("OUT_DIR") else { return };
	// OUT_DIR = .../target/<triple>/<profile>/build/aven-os-app-<hash>/out → up 2 → .../build/
	let Some(build_dir) = Path::new(&out_dir).ancestors().nth(2) else { return };
	let Ok(entries) = std::fs::read_dir(build_dir) else { return };
	for entry in entries.flatten() {
		if !entry.file_name().to_string_lossy().starts_with("llama-cpp-sys-2-") {
			continue;
		}
		let lib_dir = entry.path().join("out").join("lib");
		let Ok(libs) = std::fs::read_dir(&lib_dir) else { continue };
		for lib in libs.flatten() {
			let p = lib.path();
			let name = p.file_name().map(|s| s.to_string_lossy().into_owned()).unwrap_or_default();
			if name.starts_with("libggml") && name.ends_with(".a") {
				// Re-run if this archive changes (a future ggml rebuild restores the dups).
				println!("cargo:rerun-if-changed={}", p.display());
				if let Err(e) = uniquify_archive(&p) {
					println!("cargo:warning=ggml archive dedupe failed for {}: {e}", p.display());
				}
			}
		}
	}
}

/// Rewrite `path` in place so no two members share a name. Skips the archive symbol/string
/// table (regenerated by `ranlib`). No-op (idempotent) if the archive is already unique.
fn uniquify_archive(path: &Path) -> std::io::Result<()> {
	let bytes = std::fs::read(path)?;
	let mut archive = ar::Archive::new(std::io::Cursor::new(&bytes));
	let mut members: Vec<(String, Vec<u8>)> = Vec::new();
	let mut seen: HashMap<String, usize> = HashMap::new();
	let mut changed = false;

	while let Some(entry) = archive.next_entry() {
		let mut entry = entry?;
		let id = String::from_utf8_lossy(entry.header().identifier()).into_owned();
		// Symbol table (BSD `__.SYMDEF[ SORTED]`) / GNU index `/` + string table `//` — drop;
		// `ranlib` rebuilds the index over the rewritten members.
		if id.starts_with("__.SYMDEF") || id == "/" || id == "//" {
			continue;
		}
		let mut data = Vec::new();
		entry.read_to_end(&mut data)?;
		let n = seen.entry(id.clone()).or_insert(0);
		*n += 1;
		let unique = if *n == 1 {
			id
		} else {
			changed = true;
			match id.strip_suffix(".o") {
				Some(stem) => format!("{stem}.{n}.o"),
				None => format!("{id}.{n}"),
			}
		};
		members.push((unique, data));
	}

	if !changed {
		return Ok(()); // already unique — idempotent
	}

	let tmp = path.with_extension("a.dedup");
	{
		let mut builder = ar::Builder::new(std::fs::File::create(&tmp)?);
		for (name, data) in &members {
			let header = ar::Header::new(name.clone().into_bytes(), data.len() as u64);
			builder.append(&header, &data[..])?;
		}
	}
	std::fs::rename(&tmp, path)?;
	// Rebuild the archive symbol index so the linker can resolve members by symbol.
	let status = std::process::Command::new("ranlib").arg(path).status();
	if !matches!(status, Ok(s) if s.success()) {
		println!("cargo:warning=ranlib failed on {}", path.display());
	}
	Ok(())
}
