import type { StyleDef } from '../../engine/types.js'

const tokens: StyleDef['tokens'] = {
	'bg-a': '#FBFAF6',
	'tech-fill': 'rgba(255, 255, 255, 0.1)',
	'tech-fill-inner': 'rgba(255, 255, 255, 0.15)',
	text: '#1a1a1a',
	muted: 'rgba(26, 26, 26, 0.45)',
	border: 'rgba(0, 0, 0, 0.1)',
	'border-soft': 'color-mix(in srgb, var(--border) 35%, transparent)',
	'hitl-dash': 'color-mix(in srgb, var(--text) 20%, transparent)',
	'row-divider': 'color-mix(in srgb, var(--border) 55%, transparent)',
	'brand-accent': '#e6b34d',
	destructive: '#b45309',
	'radius-lg': '1rem',
	'radius-md': '0.75rem',
	'font-sans': "'Chillax', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
	'font-mono': 'ui-monospace, Menlo, monospace',
}

const selectors: StyleDef['selectors'] = {
	'.vs-ui-container': {
		minHeight: '100%',
		padding: '1rem 1.25rem',
		display: 'flex',
		flexDirection: 'column',
		gap: '16px',
		fontFamily: 'var(--font-sans)',
		color: 'var(--text)',
		boxSizing: 'border-box',
	},
	'.vs-header': { marginBottom: '4px' },
	'.vs-title': {
		margin: '0 0 6px 0',
		fontSize: '1.125rem',
		fontWeight: '600',
		letterSpacing: '-0.02em',
	},
	'.vs-description': {
		margin: '0',
		fontSize: '0.875rem',
		color: 'var(--muted)',
		lineHeight: '1.45',
	},
	'.vs-error': {
		margin: '0',
		fontSize: '0.875rem',
		color: 'var(--destructive)',
		display: 'none',
	},
	'.vs-error.vs-has-error': { display: 'block' },
	'.vs-add-card, .vs-list-card': {
		background: 'var(--tech-fill)',
		border: '1px dashed var(--hitl-dash)',
		borderRadius: 'var(--radius-lg)',
		padding: '16px 18px',
	},
	'.vs-section-title': {
		margin: '0 0 12px 0',
		fontSize: '0.875rem',
		fontWeight: '600',
	},
	'.vs-add-form': {
		display: 'flex',
		flexDirection: 'column',
		gap: '12px',
	},
	'.vs-field': { display: 'flex', flexDirection: 'column', gap: '4px' },
	'.vs-field-label': {
		fontSize: '0.75rem',
		color: 'var(--muted)',
	},
	'.vs-input': {
		font: 'inherit',
		color: 'inherit',
		background: 'var(--tech-fill-inner)',
		border: '1px solid var(--border-soft)',
		borderRadius: 'var(--radius-md)',
		padding: '0.55rem 0.75rem',
		outline: 'none',
	},
	'.vs-input:focus': {
		borderColor: 'var(--brand-accent)',
		boxShadow: '0 0 0 2px color-mix(in srgb, var(--brand-accent) 28%, transparent)',
	},
	'.vs-btn': {
		font: 'inherit',
		cursor: 'pointer',
		borderRadius: 'var(--radius-md)',
		padding: '0.5rem 0.85rem',
		fontWeight: '600',
		fontSize: '0.8125rem',
		border: 'none',
		background: 'transparent',
	},
	'.vs-btn--primary': {
		alignSelf: 'flex-start',
		background: 'var(--brand-accent)',
		color: 'var(--text)',
		border: '1px solid color-mix(in srgb, var(--text) 12%, transparent)',
	},
	'.vs-btn--primary:disabled': { opacity: '0.45', cursor: 'not-allowed' },
	'.vs-btn--link': {
		color: 'var(--brand-accent)',
		textDecoration: 'underline',
		padding: '0.25rem 0.5rem',
	},
	'.vs-btn--danger': {
		color: 'var(--destructive)',
		textDecoration: 'underline',
		padding: '0.25rem 0.5rem',
	},
	'.vs-loading': {
		margin: '0',
		fontSize: '0.875rem',
		color: 'var(--muted)',
		display: 'none',
	},
	'.vs-loading.vs-is-loading': { display: 'block' },
	'.vs-empty': {
		margin: '0',
		fontSize: '0.875rem',
		color: 'var(--muted)',
		textAlign: 'center',
		padding: '1.25rem 1rem',
		border: '1px dashed var(--hitl-dash)',
		borderRadius: 'var(--radius-md)',
	},
	'.vs-list:has(.vs-row) ~ .vs-empty, .vs-list-card:has(.vs-row) .vs-empty': { display: 'none' },
	'.vs-list-card:has(.vs-is-loading) .vs-list, .vs-list-card:has(.vs-is-loading) .vs-empty': {
		display: 'none',
	},
	'.vs-list': {
		listStyle: 'none',
		margin: '0',
		padding: '0',
		border: '1px solid var(--border-soft)',
		borderRadius: 'var(--radius-md)',
		overflow: 'hidden',
	},
	'.vs-row': {
		display: 'flex',
		flexWrap: 'wrap',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: '10px 16px',
		padding: '12px 14px',
		borderBottom: '1px solid var(--row-divider)',
	},
	'.vs-row:last-child': { borderBottom: 'none' },
	'.vs-row-main': { minWidth: '0', flex: '1' },
	'.vs-row-id': {
		fontFamily: 'var(--font-mono)',
		fontSize: '0.875rem',
		overflow: 'hidden',
		textOverflow: 'ellipsis',
		whiteSpace: 'nowrap',
	},
	'.vs-row-value': {
		marginTop: '6px',
		fontFamily: 'var(--font-mono)',
		fontSize: '0.75rem',
		color: 'var(--muted)',
		wordBreak: 'break-all',
	},
	'.vs-row-value.vs-hidden': { display: 'none' },
	'.vs-row-actions': {
		display: 'flex',
		flexShrink: '0',
		gap: '8px',
	},
}

export const vaultSecretsStyle: StyleDef = { tokens, selectors }
