global using Aven.WorkIntake.Contracts.Responses;
global using Aven.Contracts.Identifiers;
global using Aven.Toolkit.Core.Identifiers;
global using SchemaRef = Aven.Toolkit.Core.Identifiers.SchemaRef;
global using LlmModelCapabilities = Aven.Toolkit.Llm.LlmModelCapabilities;
global using Aven.Routing.Contracts.Enums;
global using Aven.Routing.Contracts.Models;
global using Aven.Routing.Contracts.Responses;
global using Aven.Resources.Llm.Contracts.Models;
global using Aven.Events.Interfaces;
