// AUTO-GENERATED by libs/jazz-schema/scripts/codegen-types.ts — edit schema.manifest.json then run `bun run build`

export type KeysharesRow = {
	id: string
	spark_id: string
	dek_version: number
	recipient_did: string
	wrapped_dek: string
}

export type SparksRow = {
	id: string
	spark_id: string
	name: string
	genesis_b64: string
	current_dek_version: number
	created_at_ms: number
}

export type TodosRow = {
	id: string
	spark_id: string
	title: string
	done: boolean
	description?: string | undefined
}

export type SchemaTables = {
	keyshares: KeysharesRow
	sparks: SparksRow
	todos: TodosRow
}

export type TableName = keyof SchemaTables
