// AUTO-GENERATED by libs/jazz-schema/scripts/codegen-types.ts — edit schema.manifest.json then run `bun run build`

export type HumansRow = {
	id: string
	first_name: string
	username_slug: string
	my_devices: string[]
	created_at_ms: number
}

export type KeysharesRow = {
	id: string
	spark_id: string
	dek_version: number
	recipient_did: string
	wrapped_dek: string
}

export type MessagesRow = {
	id: string
	spark_id: string
	created_at_ms: number
	author_did: string
	body: string
}

export type PeersRow = {
	id: string
	peer_did: string
	device_label: string
	kind: string
	added_at_ms: number
	status: string
}

export type SparksRow = {
	id: string
	spark_id: string
	name: string
	issuer_pubkey_b64: string
	genesis_b64: string
	current_dek_version: number
	created_at_ms: number
}

export type TodosRow = {
	id: string
	spark_id: string
	title: string
	done: boolean
	description?: string | undefined
}

export type SchemaTables = {
	humans: HumansRow
	keyshares: KeysharesRow
	messages: MessagesRow
	peers: PeersRow
	sparks: SparksRow
	todos: TodosRow
}

export type TableName = keyof SchemaTables
