// AUTO-GENERATED by libs/jazz-schema/scripts/codegen-types.ts — edit schema.manifest.json then run `bun run build`

export type TodosRow = {
	id: string
	title: string
	done: boolean
	description?: string
}

export type SchemaTables = {
	todos: TodosRow
}

export type TableName = keyof SchemaTables
