import type { StyleDef } from '../../engine/types.js'
import { invoiceStyle } from '../invoice/style.js'

// Tokens specific to the transfer list; merged on top of the invoice tokens so
// the detail pane keeps the exact invoice look and feel.
const tokens: StyleDef['tokens'] = {
	...invoiceStyle.tokens,
	'status-paid': '#2e7d52',
	'status-pending': '#e6b34d',
	'status-scheduled': '#3b82c4',
	'status-failed': '#c0392b',
	'status-overdue': '#d97706',
}

const selectors: StyleDef['selectors'] = {
	...invoiceStyle.selectors,
	':host': {
		fontFamily: 'var(--font-sans)',
		background: 'var(--bg-a)',
		color: 'var(--text)',
		margin: '0',
		height: '100%',
		minHeight: '100%',
	},
	'.bt-ui-container': {
		height: '100%',
		minHeight: '480px',
		padding: '1.25rem 1.5rem',
		borderRadius: 'var(--radius-2xl)',
		background: 'var(--tech-fill)',
		display: 'flex',
		flexDirection: 'column',
		boxSizing: 'border-box',
		fontFamily: 'var(--font-sans)',
		color: 'var(--text)',
		letterSpacing: '-0.02em',
	},
	'.bt-split': {
		display: 'grid',
		gridTemplateColumns: '1fr 1fr',
		gap: '16px',
		flex: '1',
		minHeight: '0',
	},
	'.bt-list-pane': {
		display: 'flex',
		flexDirection: 'column',
		minHeight: '0',
		background: 'var(--tech-fill)',
		border: '1px dashed var(--hitl-dash)',
		borderRadius: 'var(--radius-2xl)',
		padding: '18px 20px',
		overflow: 'hidden',
	},
	'.bt-list-header': {
		flexShrink: '0',
		marginBottom: '14px',
	},
	'.bt-eyebrow': {
		display: 'block',
		fontSize: '10px',
		fontWeight: '600',
		color: 'var(--muted)',
		textTransform: 'uppercase',
		letterSpacing: '0.12em',
		opacity: '0.55',
		marginBottom: '6px',
	},
	'.bt-list-head-row': {
		display: 'flex',
		alignItems: 'baseline',
		justifyContent: 'space-between',
		gap: '12px',
	},
	'.bt-list-title': {
		margin: '0',
		fontSize: '1.1rem',
		fontWeight: '600',
		letterSpacing: '-0.02em',
		color: 'var(--text)',
		lineHeight: '1.2',
	},
	'.bt-count': {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'flex-end',
		textAlign: 'right',
		flexShrink: '0',
	},
	'.bt-count-value': {
		fontSize: '1.35rem',
		fontWeight: '600',
		fontFamily: 'ui-monospace, Menlo, monospace',
		fontVariantNumeric: 'tabular-nums',
		color: 'var(--brand-accent)',
		lineHeight: '1.1',
	},
	'.bt-count-label': {
		fontSize: '9px',
		fontWeight: '600',
		color: 'var(--muted)',
		textTransform: 'uppercase',
		letterSpacing: '0.06em',
		marginTop: '2px',
	},
	'.bt-list': {
		listStyle: 'none',
		margin: '0',
		padding: '0',
		flex: '1',
		minHeight: '0',
		overflowY: 'auto',
		display: 'flex',
		flexDirection: 'column',
		gap: '8px',
	},
	'.bt-empty': {
		textAlign: 'center',
		color: 'var(--muted)',
		padding: '1.5rem 1rem',
		fontSize: '13px',
		border: '1px dashed var(--hitl-dash)',
		borderRadius: 'var(--radius-md)',
	},
	'.bt-list:has(.bt-row) li[data-empty="true"]': {
		display: 'none',
	},
	'.bt-row': {
		display: 'flex',
		alignItems: 'flex-start',
		gap: '12px',
		width: '100%',
		textAlign: 'left',
		font: 'inherit',
		color: 'inherit',
		cursor: 'pointer',
		background: 'var(--tech-fill-inner)',
		border: '1px solid var(--border-soft)',
		borderRadius: 'var(--radius-md)',
		padding: '12px 14px',
		transition: 'border-color 0.15s ease, background 0.15s ease, box-shadow 0.15s ease',
	},
	'.bt-row:hover': {
		borderColor: 'color-mix(in srgb, var(--text) 18%, transparent)',
		background: 'color-mix(in srgb, var(--tech-fill-inner) 55%, rgb(255 255 255))',
	},
	'.bt-row:focus-visible': {
		outline: '2px solid var(--brand-accent)',
		outlineOffset: '1px',
	},
	'.bt-row--active': {
		borderColor: 'var(--brand-accent)',
		background: 'color-mix(in srgb, var(--brand-accent) 12%, var(--tech-fill-inner))',
		boxShadow: '0 0 0 1px color-mix(in srgb, var(--brand-accent) 45%, transparent)',
	},
	'.bt-dot': {
		width: '10px',
		height: '10px',
		borderRadius: '9999px',
		flexShrink: '0',
		marginTop: '5px',
		background: 'var(--muted)',
		boxShadow: '0 0 0 3px color-mix(in srgb, var(--muted) 18%, transparent)',
	},
	'.bt-dot--paid': {
		background: 'var(--status-paid)',
		boxShadow: '0 0 0 3px color-mix(in srgb, var(--status-paid) 20%, transparent)',
	},
	'.bt-dot--pending': {
		background: 'var(--status-pending)',
		boxShadow: '0 0 0 3px color-mix(in srgb, var(--status-pending) 22%, transparent)',
	},
	'.bt-dot--scheduled': {
		background: 'var(--status-scheduled)',
		boxShadow: '0 0 0 3px color-mix(in srgb, var(--status-scheduled) 20%, transparent)',
	},
	'.bt-dot--failed': {
		background: 'var(--status-failed)',
		boxShadow: '0 0 0 3px color-mix(in srgb, var(--status-failed) 20%, transparent)',
	},
	'.bt-dot--overdue': {
		background: 'var(--status-overdue)',
		boxShadow: '0 0 0 3px color-mix(in srgb, var(--status-overdue) 20%, transparent)',
	},
	'.bt-row-body': {
		flex: '1',
		minWidth: '0',
		display: 'flex',
		flexDirection: 'column',
		gap: '3px',
	},
	'.bt-row-line': {
		display: 'flex',
		alignItems: 'baseline',
		justifyContent: 'space-between',
		gap: '10px',
	},
	'.bt-row-payee': {
		fontWeight: '600',
		fontSize: '14px',
		color: 'var(--text)',
		whiteSpace: 'nowrap',
		overflow: 'hidden',
		textOverflow: 'ellipsis',
		minWidth: '0',
	},
	'.bt-row-amount': {
		fontFamily: 'ui-monospace, Menlo, monospace',
		fontVariantNumeric: 'tabular-nums',
		fontWeight: '600',
		fontSize: '14px',
		color: 'var(--text)',
		whiteSpace: 'nowrap',
		flexShrink: '0',
	},
	'.bt-row-amount--in': {
		color: 'var(--status-paid)',
	},
	'.bt-row-ref': {
		fontSize: '12px',
		color: 'var(--muted)',
		whiteSpace: 'nowrap',
		overflow: 'hidden',
		textOverflow: 'ellipsis',
		minWidth: '0',
	},
	'.bt-row-date': {
		fontSize: '12px',
		color: 'var(--muted)',
		whiteSpace: 'nowrap',
		fontVariantNumeric: 'tabular-nums',
		flexShrink: '0',
	},
	'.bt-row-status': {
		marginTop: '2px',
		fontSize: '10px',
		fontWeight: '600',
		textTransform: 'uppercase',
		letterSpacing: '0.06em',
		color: 'var(--muted)',
	},
	'.bt-detail-pane': {
		minHeight: '0',
		overflow: 'auto',
		borderRadius: 'var(--radius-2xl)',
	},
	'.bt-detail-empty': {
		height: '100%',
		minHeight: '320px',
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		textAlign: 'center',
		border: '1px dashed var(--hitl-dash)',
		borderRadius: 'var(--radius-2xl)',
		background: 'var(--tech-fill)',
		padding: '2rem',
	},
	'.bt-detail-empty-text': {
		marginTop: '8px',
		fontSize: '13px',
		color: 'var(--muted)',
		maxWidth: '260px',
		lineHeight: '1.5',
	},
	'.bt-detail-pane[data-has-selection="true"] .bt-detail-empty': {
		display: 'none',
	},
	'.bt-detail-pane[data-has-selection="false"] .bt-detail-doc': {
		display: 'none',
	},
	'@media (max-width: 640px)': {
		'.bt-split': {
			gridTemplateColumns: '1fr',
		},
	},
}

export const bankTransfersStyle: StyleDef = {
	tokens,
	components: { ...(invoiceStyle.components ?? {}) },
	selectors,
}
