global using Aven.Contracts.Identifiers;
global using Aven.Toolkit.Core.Identifiers;
global using SchemaRef = Aven.Toolkit.Core.Identifiers.SchemaRef;
global using Aven.Contracts.Operations;
global using OperationError = Aven.Toolkit.Core.Operations.OperationError;
global using MetadataSubject = Aven.Toolkit.Metadata.MetadataSubject;
global using MetadataQuery = Aven.Toolkit.Metadata.MetadataQuery;
global using MetadataRecord = Aven.Toolkit.Metadata.MetadataRecord;
global using Aven.Resources.Metadata.Contracts.Models;
global using Aven.Events.Interfaces;
