//! `GENESIS_NETWORK_ID` is the 65-byte SEC1 uncompressed P-256 public point that anchors every
//! device identity on this network. It is **sourced from an environment variable**:
//!
//! - **release builds** read `GENESIS_NETWORK_ID`. Missing or empty = hard error.
//! - **debug builds** read `DEV_GENESIS_NETWORK_ID`. If unset, the binary generates a fresh
//!   P-256 keypair, persists *only the public bytes* to the repo-root `.env` under
//!   `DEV_GENESIS_NETWORK_ID=`, discards the private scalar, and uses it for this session.
//!
//! At runtime the public point is held in `GenesisState` (single source of truth) and read by
//! the `genesis_network_id` IPC command.

use std::fs;
use std::path::PathBuf;
use std::sync::Mutex;

use base64::{engine::general_purpose::STANDARD as B64, Engine as _};
use p256::elliptic_curve::sec1::ToEncodedPoint;
use p256::SecretKey;
use rand_core::OsRng;
use tauri::State;

#[cfg(debug_assertions)]
const ENV_VAR: &str = "DEV_GENESIS_NETWORK_ID";
#[cfg(not(debug_assertions))]
const ENV_VAR: &str = "GENESIS_NETWORK_ID";

/// Runtime cache for the active `GENESIS_NETWORK_ID` (65-byte SEC1 uncompressed P-256 point).
#[derive(Default)]
pub struct GenesisState {
	pub_bytes: Mutex<Option<Vec<u8>>>,
}

impl GenesisState {
	pub fn set(&self, bytes: Vec<u8>) {
		*self.pub_bytes.lock().unwrap() = Some(bytes);
	}

	pub fn get(&self) -> Option<Vec<u8>> {
		self.pub_bytes.lock().unwrap().clone()
	}
}

fn decode_env_value(raw: &str) -> Result<Vec<u8>, String> {
	let trimmed = raw.trim().trim_matches('"').trim_matches('\'');
	let bytes = B64
		.decode(trimmed.as_bytes())
		.map_err(|e| format!("{ENV_VAR} base64 decode: {e}"))?;
	if bytes.len() != 65 {
		return Err(format!(
			"{ENV_VAR} expected 65-byte SEC1 uncompressed P-256 public point, got {} bytes",
			bytes.len()
		));
	}
	Ok(bytes)
}

fn generate_new_pub() -> Vec<u8> {
	let sk = SecretKey::random(&mut OsRng);
	let pk = sk.public_key();
	pk.to_encoded_point(false).as_bytes().to_vec()
	// `sk` drops here — private scalar never leaves this function or persists.
}

/// Walk up from `CARGO_MANIFEST_DIR` looking for a `.env` file. Returns the **path to use**:
/// the first existing `.env`, or the workspace root (highest directory containing `package.json`)
/// if no `.env` exists yet.
fn locate_repo_env_path() -> Option<PathBuf> {
	let mut dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
	let mut workspace_root: Option<PathBuf> = None;
	loop {
		let env_path = dir.join(".env");
		if env_path.is_file() {
			return Some(env_path);
		}
		if dir.join("package.json").is_file() {
			workspace_root = Some(dir.clone());
		}
		if !dir.pop() {
			break;
		}
	}
	workspace_root.map(|p| p.join(".env"))
}

/// Upsert `<ENV_VAR>="<b64>"` in the env file. Creates the file if missing.
fn persist_to_env_file(path: &PathBuf, b64: &str) -> Result<(), String> {
	let line = format!("{ENV_VAR}=\"{b64}\"");
	let existing = fs::read_to_string(path).unwrap_or_default();

	let mut rewrote = false;
	let mut lines: Vec<String> = existing
		.lines()
		.map(|l| {
			if l.trim_start().starts_with(&format!("{ENV_VAR}=")) {
				rewrote = true;
				line.clone()
			} else {
				l.to_string()
			}
		})
		.collect();

	if !rewrote {
		if !existing.is_empty() && !existing.ends_with('\n') {
			lines.push(String::new());
		}
		lines.push(format!(
			"\n# Auto-generated by AvenOS — genesis network id (P-256 public anchor, 65-byte SEC1)."
		));
		lines.push(line);
	}

	let mut out = lines.join("\n");
	if !out.ends_with('\n') {
		out.push('\n');
	}

	if let Some(parent) = path.parent() {
		fs::create_dir_all(parent).map_err(|e| format!("create_dir_all {}: {e}", parent.display()))?;
	}
	fs::write(path, out).map_err(|e| format!("write {}: {e}", path.display()))?;
	Ok(())
}

/// Called once during Tauri setup. Populates `GenesisState`.
pub fn bootstrap(state: &GenesisState) -> Result<(), String> {
	if let Ok(raw) = std::env::var(ENV_VAR) {
		if !raw.trim().is_empty() {
			let bytes = decode_env_value(&raw)?;
			log::info!("{ENV_VAR} loaded from env ({} bytes)", bytes.len());
			state.set(bytes);
			return Ok(());
		}
	}

	if !cfg!(debug_assertions) {
		return Err(format!(
			"{ENV_VAR} not set — release builds require an injected genesis network id."
		));
	}

	let pub_bytes = generate_new_pub();
	let b64 = B64.encode(&pub_bytes);
	let env_path = locate_repo_env_path()
		.unwrap_or_else(|| PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(".env"));

	persist_to_env_file(&env_path, &b64)?;
	// Reflect into the current process so any later `std::env::var` reads see it too.
	std::env::set_var(ENV_VAR, &b64);

	log::info!(
		"{ENV_VAR} generated and persisted to {} ({} bytes)",
		env_path.display(),
		pub_bytes.len()
	);
	state.set(pub_bytes);
	Ok(())
}

#[tauri::command]
pub async fn genesis_network_id(state: State<'_, GenesisState>) -> Result<Vec<u8>, String> {
	state.get().ok_or_else(|| {
		format!("genesis not initialised: set {ENV_VAR} (base64 SEC1 uncompressed P-256 public point)")
	})
}
