#!/usr/bin/env bun
/**
 * Generates types.ts from schema.manifest.json (single source shared with Rust).
 */
import manifest from "../schema.manifest.json" with { type: "json" }

type Col = {
	name: string
	type: string
	nullable?: boolean
	plaintext?: boolean
}
type Manifest = {
	tables: Record<string, { columns: Col[] }>
}

function tsScalar(t: string, nullable: boolean): string {
	const base =
		t === "text"
			? "string"
			: t === "boolean"
				? "boolean"
				: t === "integer"
					? "number"
					: t === "bigint"
						? "number"
						: "string"
		return nullable ? `${base}` : base
}

const m = manifest as Manifest

const rowTypes: string[] = []
const unionNames: string[] = []

for (const table of Object.keys(m.tables).sort()) {
	unionNames.push(`'${table}'`)
	const def = m.tables[table]
	if (!def.columns?.length) throw new Error(`table ${table} has no columns`)
	const fields = def.columns.map((col) => {
		const nullable = Boolean(col.nullable)
		const q = nullable ? "?" : ""
		return `\t${col.name}${q}: ${tsScalar(col.type, nullable)}`
	})
	const pname = `${table.slice(0, 1).toUpperCase()}${table.slice(1)}Row`
	rowTypes.push(`export type ${pname} = {\n\tid: string\n${fields.join("\n")}\n}`)
}

const tableMap = Object.keys(m.tables)
	.sort()
	.map((table) => {
		const pname = `${table.slice(0, 1).toUpperCase()}${table.slice(1)}Row`
		return `\t${table}: ${pname}`
	})
	.join("\n")

const out = `// AUTO-GENERATED by libs/jazz-schema/scripts/codegen-types.ts — edit schema.manifest.json then run \`bun run build\`\n\n${rowTypes.join("\n\n")}\n\nexport type SchemaTables = {\n${tableMap}\n}\n\nexport type TableName = keyof SchemaTables\n`

import { mkdir, writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const dir = dirname(fileURLToPath(import.meta.url))
const dest = join(dir, "..", "types.ts")
await writeFile(dest, out, "utf8")
console.log(`Wrote ${dest}`)
