#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<SQL
CREATE ROLE aven_migrator LOGIN PASSWORD '${AVEN_MIGRATOR_PASSWORD}';
CREATE ROLE aven_server LOGIN PASSWORD '${AVEN_SERVER_PASSWORD}';
CREATE ROLE aven_email_worker LOGIN PASSWORD '${AVEN_EMAIL_WORKER_PASSWORD}';
CREATE ROLE aven_environment_worker LOGIN PASSWORD '${AVEN_ENVIRONMENT_WORKER_PASSWORD}';
CREATE ROLE aven_provisioner LOGIN PASSWORD '${AVEN_PROVISIONER_PASSWORD}' CREATEDB CREATEROLE;
ALTER DATABASE "$POSTGRES_DB" OWNER TO aven_migrator;
ALTER SCHEMA public OWNER TO aven_migrator;
SQL
