global using Aven.Contracts.Identifiers;
global using SchemaRef = Aven.Toolkit.Core.Identifiers.SchemaRef;
global using Aven.Contracts.Operations;
global using OperationError = Aven.Toolkit.Core.Operations.OperationError;
global using OperationValue = Aven.Toolkit.Core.Operations.OperationValue;
global using Aven.DurableDelivery.Contracts.Enums;
global using Aven.Scheduling.Contracts.Commands;
global using Aven.Scheduling.Contracts.Enums;
global using Aven.Scheduling.Contracts.Models;
global using Aven.Scheduling.Contracts.Responses;
global using Aven.Events.Interfaces;
